services:

  apiGateway:
    image: apigateway:latest
    restart: always
    ports:
      - 8080:8080
    environment:
      SERVER_PORT: 8080
    networks:
      - localnetwork

  account:
    image: account-service:latest
    restart: always
    environment:
      SERVER_PORT: 9090
    networks:
      - localnetwork

  profile:
    image: profile-service:latest
    restart: always
    environment:
      SERVER_PORT: 9091
    networks:
      - localnetwork

  product:
    image: product-service:latest
    restart: always
    environment:
      SERVER_PORT: 9092
    networks:
      - localnetwork

  creditCard:
    image: creditcard-service:latest
    restart: always
    environment:
      SERVER_PORT: 9093
    networks:
      - localnetwork

  cart:
    image: cart-service:latest
    restart: always
    environment:
      SERVER_PORT: 9094
    networks:
      - localnetwork

  order:
    image: order-service:latest
    restart: always
    environment:
      SERVER_PORT: 9095
    networks:
      - localnetwork

networks:
  localnetwork:
    driver: bridge
    
    
