spring:

  application:
    name: ApiGateway

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

server:
  port: 8080

app:
  service:
    account: http://account:9090
    profile: http://profile:9091
    product: http://product:9092
    creditCard: http://creditCard:9093
    cart: http://cart:9094
    order: http://order:9095


zuul:
  #prefix: /superMarket
  routes:
    account:
      path: /account/**
      url: ${app.service.account}
    profile:
      path: /profile/**
      url: ${app.service.profile}
    product:
      path: /product/**
      url: ${app.service.product}
    creditCard:
      path: /creditCard/**
      url: ${app.service.creditCard}
    cart:
      path: /cart/**
      url: ${app.service.cart}
    order:
      path: /order/**
      url: ${app.service.order}
    

